services:

  grafana:
    container_name: grafana
    image: grafana/grafana-oss:latest
    volumes:
      - grafana-data:/var/lib/grafana
      - grafana-etc:/etc/grafana
    environment:
      - GF_SECURITY_ALLOW_EMBEDDING=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_NAME=Viewer
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer
    ports:
      - "3000:3000"
    restart: always
    user: "grafana"
    labels:
      - docker-volume-backup.stop-during-backup=service1_DONOTSTOP

  backup:
    container_name: grafana-backup
    image: offen/docker-volume-backup:v2
    environment:
      BACKUP_STOP_DURING_BACKUP_LABEL: service1
      BACKUP_FILENAME: backup-grafana-%Y-%m-%dT%H-%M-%S.tar.gz
      BACKUP_LATEST_SYMLINK: backup-grafana-latest.tar.gz
      BACKUP_CRON_EXPRESSION: "5 5 * * 1"
      BACKUP_PRUNING_PREFIX: "backup-grafana-"
      BACKUP_RETENTION_DAYS: 30
      SSH_HOST_NAME: ${SSH_HOST_NAME}
      SSH_PORT: 22
      SSH_REMOTE_PATH: "/iot/backup/"
      SSH_USER: ${SSH_USER}
      SSH_PASSWORD: ${SSH_PASSWORD}
    restart: always
    volumes:
      - grafana-data:/backup/lib:ro
      - grafana-etc:/backup/etc:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/localtime:/etc/localtime:ro

volumes:
    grafana-data:
        name: grafana-data
    grafana-etc:
        name: grafana-etc