{
 "title": "BLE Temperature/Humidity incl batteries",
 "tags": [ "ble" ],
 "time": { "from": "now-12h", "to": "now" },
 "panels": [
  {
   "title": "Temperatuur",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "import \"sql\"\r\nimport \"join\"\r\nimport \"influxdata/influxdb/secrets\"\r\n\r\nusername = secrets.get(key: \"MYSQL_USERNAME\")\r\npassword = secrets.get(key: \"MYSQL_PASSWORD\")\r\nmysql_server = secrets.get(key: \"MYSQL_SERVER\")\r\n\r\nble = sql.from(\r\n    driverName: \"mysql\",\r\n    dataSourceName: \"${username}:${password}@tcp(${mysql_server})/sensor\",\r\n    query: \"SELECT UPPER(mac) as topic, location as location FROM device WHERE model = 'LYWSD03MMC_ATC' LIMIT 50\",\r\n)\r\n\r\ndata = from(bucket: \"Residence\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"protocol\"] == \"ble\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Temperature\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"temperature\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> group()\r\n\r\njoin.inner(\r\n    left: data,\r\n    right: ble,\r\n    on: (l, r) => l.topic == r.topic,\r\n    as: (l, r) => ({l with location: r.location}),\r\n)\r\n  |> group(columns: [\"_time\", \"_value\"], mode: \"except\")\r\n"
    }
   ]
  },
  {
   "title": "Relative Humidity",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "query": "import \"sql\"\r\nimport \"join\"\r\nimport \"influxdata/influxdb/secrets\"\r\n\r\nusername = secrets.get(key: \"MYSQL_USERNAME\")\r\npassword = secrets.get(key: \"MYSQL_PASSWORD\")\r\nmysql_server = secrets.get(key: \"MYSQL_SERVER\")\r\n\r\nble = sql.from(\r\n    driverName: \"mysql\",\r\n    dataSourceName: \"${username}:${password}@tcp(${mysql_server})/sensor\",\r\n    query: \"SELECT UPPER(mac) as topic, location as location FROM device WHERE model = 'LYWSD03MMC_ATC' LIMIT 50\",\r\n)\r\n\r\ndata = from(bucket: \"Residence\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"protocol\"] == \"ble\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Humidity\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"humidity\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> group()\r\n\r\njoin.inner(\r\n    left: data,\r\n    right: ble,\r\n    on: (l, r) => l.topic == r.topic,\r\n    as: (l, r) => ({l with location: r.location}),\r\n)\r\n  |> group(columns: [\"_time\", \"_value\"], mode: \"except\")\r\n"
    }
   ]
  },
  {
   "title": "Voltage",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"sql\"\r\nimport \"join\"\r\nimport \"influxdata/influxdb/secrets\"\r\n\r\nusername = secrets.get(key: \"MYSQL_USERNAME\")\r\npassword = secrets.get(key: \"MYSQL_PASSWORD\")\r\nmysql_server = secrets.get(key: \"MYSQL_SERVER\")\r\n\r\nble = sql.from(\r\n    driverName: \"mysql\",\r\n    dataSourceName: \"${username}:${password}@tcp(${mysql_server})/sensor\",\r\n    query: \"SELECT UPPER(mac) as topic, location as location FROM device WHERE model = 'LYWSD03MMC_ATC' LIMIT 50\",\r\n)\r\n\r\ndata = from(bucket: \"Residence\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"protocol\"] == \"ble\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Power\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"voltage\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> group()\r\n\r\njoin.inner(\r\n    left: data,\r\n    right: ble,\r\n    on: (l, r) => l.topic == r.topic,\r\n    as: (l, r) => ({l with location: r.location}),\r\n)\r\n  |> group(columns: [\"_time\", \"_value\"], mode: \"except\")\r\n"
    }
   ]
  },
  {
   "title": "# records",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"sql\"\r\nimport \"join\"\r\nimport \"influxdata/influxdb/secrets\"\r\n\r\nusername = secrets.get(key: \"MYSQL_USERNAME\")\r\npassword = secrets.get(key: \"MYSQL_PASSWORD\")\r\nmysql_server = secrets.get(key: \"MYSQL_SERVER\")\r\n\r\nble = sql.from(\r\n    driverName: \"mysql\",\r\n    dataSourceName: \"${username}:${password}@tcp(${mysql_server})/sensor\",\r\n    query: \"SELECT UPPER(mac) as topic, location as location FROM device WHERE model = 'LYWSD03MMC_ATC' LIMIT 50\",\r\n)\r\n\r\ndata = from(bucket: \"Residence\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"protocol\"] == \"ble\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Power\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"voltage\")\r\n  |> aggregateWindow(every: 24h, fn: count, createEmpty: false)\r\n  |> group()\r\n\r\njoin.inner(\r\n    left: data,\r\n    right: ble,\r\n    on: (l, r) => l.topic == r.topic,\r\n    as: (l, r) => ({l with location: r.location}),\r\n)\r\n  |> group(columns: [\"_time\", \"_value\"], mode: \"except\")\r\n"
    }
   ]
  }
 ]
}