{
 "title": "Nefit Status",
 "description": "Nefit Thermostat info",
 "tags": [ "Nefit" ],
 "time": { "from": "2024-12-31T23:00:00.000Z", "to": "2025-12-31T22:59:59.000Z" },
 "panels": [
  {
   "title": "Nefit Inhouse temperature",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"Residence\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Status\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"temp_inhouse\" or r[\"_field\"] == \"temp_setpoint\")\r\n  |> filter(fn: (r) => r[\"protocol\"] == \"nefit\")\r\n  |> filter(fn: (r) => r[\"topic\"] == \"Nefit\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Boiler",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"Residence\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Status\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"boiler\")\r\n  |> filter(fn: (r) => r[\"protocol\"] == \"nefit\")\r\n  |> filter(fn: (r) => r[\"topic\"] == \"Nefit\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)\r\n  |> yield(name: \"boiler\")"
    }
   ]
  },
  {
   "title": "Nefit jaren",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "query": "import \"date\"\r\nimport \"timezone\"\r\noption location = timezone.location(name: \"Europe/Amsterdam\")\r\n\r\nfrom(bucket: \"Residence\")\r\n  |> range(start: date.sub(d: 1mo, from: date.truncate(t: -3y, unit: 1y)), stop: date.truncate(t: -2y, unit: 1y))\r\n  |> timeShift(duration: 3y)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"GasUsage\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"central_heating\")\r\n  |> aggregateWindow(every: 1d, fn: mean, createEmpty: false)\r\n  |> movingAverage(n: 4)\r\n  |> rename(columns: {_value: \"-3yr\"})\r\n  |> yield(name: \"-3yr\")"
    },
    {
     "query": "import \"date\"\r\nimport \"timezone\"\r\noption location = timezone.location(name: \"Europe/Amsterdam\")\r\n\r\nfrom(bucket: \"Residence\")\r\n  |> range(start: date.sub(d: 1mo, from: date.truncate(t: -2y, unit: 1y)), stop: date.truncate(t: -1y, unit: 1y))\r\n  |> timeShift(duration: 2y)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"GasUsage\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"central_heating\")\r\n  |> aggregateWindow(every: 1d, fn: mean, createEmpty: false)\r\n  |> movingAverage(n: 4)\r\n  |> rename(columns: {_value: \"-2yr\"})\r\n  |> yield(name: \"-2yr\")"
    },
    {
     "query": "import \"date\"\r\nimport \"timezone\"\r\noption location = timezone.location(name: \"Europe/Amsterdam\")\r\n\r\nfrom(bucket: \"Residence\")\r\n  |> range(start: date.sub(d: 1mo, from: date.truncate(t: -1y, unit: 1y)), stop: date.truncate(t: now(), unit: 1y))\r\n  |> timeShift(duration: 1y)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"GasUsage\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"central_heating\")\r\n  |> aggregateWindow(every: 1d, fn: mean, createEmpty: false)\r\n  |> movingAverage(n: 4)\r\n  |> rename(columns: {_value: \"-1yr\"})\r\n  |> yield(name: \"mean\")"
    },
    {
     "query": "import \"date\"\r\nimport \"timezone\"\r\noption location = timezone.location(name: \"Europe/Amsterdam\")\r\n\r\nfrom(bucket: \"Residence\")\r\n  |> range(start: date.sub(d: 1mo, from: date.truncate(t: now(), unit: 1y)), stop: date.truncate(t: 1y, unit: 1y))\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"GasUsage\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"central_heating\")\r\n  |> aggregateWindow(every: 1d, fn: mean, createEmpty: false)\r\n  |> movingAverage(n: 4)\r\n  |> rename(columns: {_value: \"cy\"})\r\n  |> yield(name: \"mean\")"
    }
   ]
  }
 ]
}