{
 "title": "Powergas",
 "tags": [ "p1mon" ],
 "time": { "from": "now-2y", "to": "now" },
 "panels": [
  {
   "title": "Wekelijks stroom consumptie/productie",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "query": "from(bucket: \"Residence\")\r\n  |> range(start: 2021-01-01, stop: 2025-12-31)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Powergas\")\r\n  |> filter(fn: (r) => r[\"duration\"] == \"day\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"consumption_delta_kwh\" or r[\"_field\"] == \"production_delta_kwh\")\r\n  |> aggregateWindow(every: 1w, fn: sum, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Wekelijks gas consumptie",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "m3" } },
   "targets": [
    {
     "query": "from(bucket: \"Residence\")\r\n  |> range(start: 2021-01-01, stop: 2025-12-31)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Powergas\")\r\n  |> filter(fn: (r) => r[\"duration\"] == \"day\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"consumption_gas_delta_m3\")\r\n  |> aggregateWindow(every: 1w, fn: sum, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Wekelijks stroom consumptie/productie obv hour",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "query": "from(bucket: \"Residence\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Powergas\")\r\n  |> filter(fn: (r) => r[\"duration\"] == \"hour\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"consumption_delta_kwh\" or r[\"_field\"] == \"production_delta_kwh\")\r\n  |> aggregateWindow(every: 1d, fn: sum, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Gas consumptie obv hour",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "m3" } },
   "targets": [
    {
     "query": "import \"timezone\"\r\noption location = timezone.location(name: \"Europe/Amsterdam\")\r\n\r\nfrom(bucket: \"Residence\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Powergas\")\r\n  |> filter(fn: (r) => r[\"duration\"] == \"hour\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"consumption_gas_delta_m3\")\r\n  |> aggregateWindow(every: 1d, fn: sum, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Stroom consumptie/productie obv minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "query": "from(bucket: \"Residence\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Powergas\")\r\n  |> filter(fn: (r) => r[\"duration\"] == \"minute\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"consumption_delta_kwh\" or r[\"_field\"] == \"production_delta_kwh\")\r\n  |> aggregateWindow(every: 1m, fn: mean, createEmpty: true)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Gas consumptie obv minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "m3" } },
   "targets": [
    {
     "query": "from(bucket: \"Residence\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Powergas\")\r\n  |> filter(fn: (r) => r[\"duration\"] == \"minute\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"consumption_gas_delta_m3\")\r\n  |> aggregateWindow(every: 1m, fn: mean, createEmpty: true)\r\n  |> yield(name: \"mean\")"
    }
   ]
  }
 ]
}