{
 "title": "Watermeter",
 "tags": [ "p1mon" ],
 "time": { "from": "now-6M", "to": "now" },
 "panels": [
  {
   "title": "Watermeter",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "m3" } },
   "targets": [
    {
     "query": "from(bucket: \"Residence\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Watermeter\")\r\n  |> filter(fn: (r) => r[\"duration\"] == \"day\")\r\n  |> filter(fn: (r) => r[\"topic\"] == \"pi58\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"watermeter_consumption_total_m3\")\r\n  |> aggregateWindow(every: 1d, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Watermeter day",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "litre" } },
   "targets": [
    {
     "query": "from(bucket: \"Residence\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Watermeter\")\r\n  |> filter(fn: (r) => r[\"duration\"] == \"day\")\r\n  |> filter(fn: (r) => r[\"topic\"] == \"pi58\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"watermeter_consumption_liter\")\r\n  |> aggregateWindow(every: 1d, fn: sum, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Watermeter hour",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "litre" } },
   "targets": [
    {
     "query": "import \"timezone\"\r\noption location = timezone.location(name: \"Europe/Amsterdam\")\r\n\r\nhour_water = from(bucket: \"Residence\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Watermeter\")\r\n  |> filter(fn: (r) => r[\"duration\"] == \"hour\")\r\n  |> filter(fn: (r) => r[\"topic\"] == \"pi58\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"watermeter_consumption_liter\")\r\n  |> aggregateWindow(every: 1h, fn: sum, createEmpty: false)\r\n\r\nhour_water\r\n  |> hourSelection(start: 0, stop: 5)\r\n  |> map(fn: (r) => ({ r with duration: \"nacht\" }))\r\n  |> yield(name: \"nacht\")\r\n\r\nhour_water\r\n  |> hourSelection(start: 6, stop: 11)\r\n  |> map(fn: (r) => ({ r with duration: \"ochtend\" }))\r\n  |> yield(name: \"ochtend\")\r\n\r\nhour_water\r\n  |> hourSelection(start: 12, stop: 17)\r\n  |> map(fn: (r) => ({ r with duration: \"middag\" }))\r\n  |> yield(name: \"middag\")\r\n\r\nhour_water\r\n  |> hourSelection(start: 18, stop: 23)\r\n  |> map(fn: (r) => ({ r with duration: \"avond\" }))\r\n  |> yield(name: \"avond\")\r\n  \r\n"
    }
   ]
  },
  {
   "title": "Maximum liter per minuut",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "litre" } },
   "targets": [
    {
     "query": "from(bucket: \"Residence\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Watermeter\")\r\n  |> filter(fn: (r) => r[\"duration\"] == \"minute\")\r\n  |> filter(fn: (r) => r[\"topic\"] == \"pi58\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"watermeter_consumption_liter\")\r\n  |> aggregateWindow(every: 30m, fn: max, createEmpty: false)\r\n  |> yield(name: \"sum\")"
    }
   ]
  }
 ]
}